In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
data=pd.read_csv("quikr_car.csv")
df=pd.DataFrame(data)
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [3]:
df.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

# Problems in Dataset

- Year has many non year values and its data type is object (convert into date)

- Price column have abitary values (ask for price) and its data type is also object 

- kms_driven have comas and datatype of object should be converted into integer and also has nan values

- fuel_type have nan values

- Keep 3 words of name (cux its ajeeb si values eg.Hyundai Santro Xing XO eRLX Euro III)

- company have many arbitary values

# Cleaning dataset

## Year

In [5]:
# create backup of dataset 
backup=df.copy()

In [6]:
df=df[df["year"].str.isnumeric()] # year mai se non numeric values delete

In [7]:
df["year"]=df["year"].astype(int) #values is converted to integer

C:\Users\bhand\AppData\Local\Temp\ipykernel_18760\483452920.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["year"]=df["year"].astype(int) #values is converted to integer

## price

In [8]:
df=df[df["Price"]!="Ask For Price"] #Only numeric values

In [9]:
df["Price"]=df["Price"].str.replace(",","")

In [10]:
df["Price"]=df["Price"].astype(int)

## Kms_driven

In [11]:
df["kms_driven"]

0        45,000 kms
1            40 kms
3        28,000 kms
4        36,000 kms
6        41,000 kms
           ...
886    1,32,000 kms
888      27,000 kms
889      40,000 kms
890          Petrol
891          Petrol
Name: kms_driven, Length: 819, dtype: object

In [12]:
#type change
df["kms_driven"]=df["kms_driven"].str.split(" ").str.get(0).str.replace(",","")

In [13]:
df=df[df["kms_driven"].str.isnumeric()]

In [14]:
df["kms_driven"]=df["kms_driven"].astype(int)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.7+ KB

## Fuel type

In [16]:
df=df[~df["fuel_type"].isna()]

In [17]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

## Name

In [18]:
df["name"]=df["name"].str.split().str.slice(0,3).str.join(" ")

In [19]:
df=df.reset_index()

In [20]:
df

,index,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550,Mahindra,2006,425000,40,Diesel
2,3,Hyundai Grand i10,Hyundai,2014,325000,28000,Petrol
3,4,Ford EcoSport Titanium,Ford,2014,575000,36000,Diesel
4,6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
811,883,Maruti Suzuki Ritz,Maruti,2011,270000,50000,Petrol
812,885,Tata Indica V2,Tata,2009,110000,30000,Diesel
813,886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
814,888,Tata Zest XM,Tata,2018,260000,27000,Diesel
815,889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       816 non-null    int64
 1   name        816 non-null    object
 2   company     816 non-null    object
 3   year        816 non-null    int64
 4   Price       816 non-null    int64
 5   kms_driven  816 non-null    int64
 6   fuel_type   816 non-null    object
dtypes: int64(4), object(3)
memory usage: 44.8+ KB

In [22]:
df.describe()

            index         year         Price     kms_driven
count  816.000000   816.000000  8.160000e+02     816.000000
mean   431.637255  2012.444853  4.117176e+05   46275.531863
std    254.197374     4.002992  4.751844e+05   34297.428044
min      0.000000  1995.000000  3.000000e+04       0.000000
25%    212.750000  2010.000000  1.750000e+05   27000.000000
50%    427.500000  2013.000000  2.999990e+05   41000.000000
75%    652.250000  2015.000000  4.912500e+05   56818.500000
max    889.000000  2019.000000  8.500003e+06  400000.000000

## Outliers Detection

In [23]:
df["Price"].mean()

np.float64(411717.61519607843)

In [24]:
px.box(data_frame=df,x="Price")

In [25]:
df["Price"].skew()

np.float64(7.521224840597819)

In [26]:
Q3=df["Price"].quantile(0.75)
Q1=df["Price"].quantile(0.25)
print(Q3,Q1)

491250.0 175000.0

In [27]:
IQR=Q3-Q1
print("Iqr is : ",IQR)

Iqr is :  316250.0

In [28]:
upper_limit=Q3+(1.5*IQR)
lower_limit=Q1-(1.5*IQR)
print("upper_limit : ",upper_limit)
print("lower_limit : ",lower_limit) #no left side outliers

upper_limit :  965625.0
lower_limit :  -299375.0

In [29]:
df=df[df["Price"]<upper_limit]

In [30]:
px.box(x=df["Price"])

In [31]:
df

,index,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550,Mahindra,2006,425000,40,Diesel
2,3,Hyundai Grand i10,Hyundai,2014,325000,28000,Petrol
3,4,Ford EcoSport Titanium,Ford,2014,575000,36000,Diesel
4,6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
811,883,Maruti Suzuki Ritz,Maruti,2011,270000,50000,Petrol
812,885,Tata Indica V2,Tata,2009,110000,30000,Diesel
813,886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
814,888,Tata Zest XM,Tata,2018,260000,27000,Diesel
815,889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

## Model

In [32]:
x=df.drop(columns=["Price"])
y=df["Price"]

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [34]:
x_train

     index                  name    company  year  kms_driven fuel_type
357    372  Tata Vista Quadrajet       Tata  2011       90000    Diesel
776    843    Maruti Suzuki Alto     Maruti  2019        1500    Petrol
307    320        Renault Duster    Renault  2015       49000    Diesel
737    784   Maruti Suzuki Swift     Maruti  2011       58000    Diesel
95      99     Chevrolet Beat LT  Chevrolet  2012       45000    Diesel
..     ...                   ...        ...   ...         ...       ...
74      77           Honda Amaze      Honda  2015       22000    Petrol
112    116  Maruti Suzuki Esteem     Maruti  2007       51000    Petrol
284    296    Mahindra TUV300 T4   Mahindra  2016        9000    Diesel
463    487  Maruti Suzuki Ertiga     Maruti  2015       75000    Petrol
108    112      Hyundai i20 Asta    Hyundai  2012       36200    Diesel

[610 rows x 6 columns]

In [35]:
y_train

357    120000
776    400000
307    449999
737    250000
95     135000
        ...
74     344999
112     69999
284    675000
463    550000
108    329500
Name: Price, Length: 610, dtype: int64

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline

In [37]:
ohe=OneHotEncoder()
ohe.fit(x[["name","company","fuel_type"]])

OneHotEncoder()

In [38]:
ohe.categories_

[array(['Audi A4 1.8', 'Audi Q7', 'BMW 3 Series', 'BMW 5 Series',
        'Chevrolet Beat', 'Chevrolet Beat Diesel', 'Chevrolet Beat LS',
        'Chevrolet Beat LT', 'Chevrolet Beat PS', 'Chevrolet Cruze LTZ',
        'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4', 'Chevrolet Sail 1.2',
        'Chevrolet Sail UVA', 'Chevrolet Spark', 'Chevrolet Spark 1.0',
        'Chevrolet Spark LS', 'Chevrolet Spark LT', 'Chevrolet Tavera LS',
        'Chevrolet Tavera Neo', 'Datsun GO T', 'Datsun Go Plus',
        'Datsun Redi GO', 'Fiat Linea Emotion', 'Fiat Petra ELX',
        'Fiat Punto Emotion', 'Force Motors Force', 'Force Motors One',
        'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend', 'Ford Fiesta',
        'Ford Fiesta SXi', 'Ford Figo', 'Ford Figo Diesel',
        'Ford Figo Duratorq', 'Ford Figo Petrol', 'Ford Fusion 1.4',
        'Ford Ikon 1.3', 'Ford Ikon 1.6', 'Hindustan Motors Ambassador',
        'Honda Accord', 'Honda Amaze', 'Honda Amaze 1.2',
        'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V', 'Honda Brio VX',
        'Honda City', 'Honda City 1.5', 'Honda City SV', 'Honda City VX',
        'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX', 'Honda Mobilio',
        'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jeep Wrangler Unlimited', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra Thar CRDe',
        'Mahindra XUV500', 'Mahindra XUV500 W6', 'Mahindra XUV500 W8',
        'Mahindra Xylo D2', 'Mahindra Xylo E4', 'Mahindra Xylo E8',
        'Maruti Suzuki 800', 'Maruti Suzuki A', 'Maruti Suzuki Alto',
        'Maruti Suzuki Baleno', 'Maruti Suzuki Celerio',
        'Maruti Suzuki Ciaz', 'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz C', 'Mitsubishi Lancer 1.8', 'Nissan Micra XL',
        'Nissan Micra XV', 'Nissan Sunny', 'Nissan Sunny XL',
        'Nissan Terrano XL', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner 3.0', 'Toyota Innova 2.0',
        'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jeep', 'Mahindra', 'Maruti',
        'Mercedes', 'Mitsubishi', 'Nissan', 'Renault', 'Skoda', 'Tata',
        'Toyota', 'Volkswagen'], dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [39]:
col_trf=ColumnTransformer(transformers=[("trf1",OneHotEncoder(categories=ohe.categories_),["name","company","fuel_type"])],remainder="passthrough")

In [40]:
col_trf

ColumnTransformer(remainder='passthrough',
                  transformers=[('trf1',
                                 OneHotEncoder(categories=[array(['Audi A4 1.8', 'Audi Q7', 'BMW 3 Series', 'BMW 5 Series',
       'Chevrolet Beat', 'Chevrolet Beat Diesel', 'Chevrolet Beat LS',
       'Chevrolet Beat LT', 'Chevrolet Beat PS', 'Chevrolet Cruze LTZ',
       'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4', 'Chevrolet Sail 1.2',
       'Chevrolet Sail UVA', 'Chevrolet Spark', 'C...
       'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
       'Volkswagen Vento Konekt'], dtype=object),
                                                           array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jeep', 'Mahindra', 'Maruti',
       'Mercedes', 'Mitsubishi', 'Nissan', 'Renault', 'Skoda', 'Tata',
       'Toyota', 'Volkswagen'], dtype=object),
                                                           array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                 ['name', 'company', 'fuel_type'])])

In [41]:
lr=LinearRegression()

In [42]:
pipe=make_pipeline(col_trf,lr)

In [43]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf1',
                                                  OneHotEncoder(categories=[array(['Audi A4 1.8', 'Audi Q7', 'BMW 3 Series', 'BMW 5 Series',
       'Chevrolet Beat', 'Chevrolet Beat Diesel', 'Chevrolet Beat LS',
       'Chevrolet Beat LT', 'Chevrolet Beat PS', 'Chevrolet Cruze LTZ',
       'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4', 'Chevrolet Sail 1.2',
       '...
       'Volkswagen Vento Konekt'], dtype=object),
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jeep', 'Mahindra', 'Maruti',
       'Mercedes', 'Mitsubishi', 'Nissan', 'Renault', 'Skoda', 'Tata',
       'Toyota', 'Volkswagen'], dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [46]:
y_pred=pipe.predict(x_test)

In [47]:
print(r2_score(y_pred,y_test))

0.6773206914338885

In [48]:
df

,index,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550,Mahindra,2006,425000,40,Diesel
2,3,Hyundai Grand i10,Hyundai,2014,325000,28000,Petrol
3,4,Ford EcoSport Titanium,Ford,2014,575000,36000,Diesel
4,6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
811,883,Maruti Suzuki Ritz,Maruti,2011,270000,50000,Petrol
812,885,Tata Indica V2,Tata,2009,110000,30000,Diesel
813,886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
814,888,Tata Zest XM,Tata,2018,260000,27000,Diesel
815,889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel